### ISSUE TITLE
Decision tree

### ISSUE THREAD

**Issue by panterz** [edina/fieldtrip-cobweb-project#42]
Simplification and documentation of the d-tree implementation on FTOpen. Visualization of the data captured as well.

**Comment by rgamez** [comment]
From a Chrona bug report

- [ ] Does not allow a second observation to be recorded
- [ ] Spelling of 'Dward' shoud be corrected to 'Dwarf'
- [ ] Looks like questions that should just pertain to trees (e.g. broadleaved/coniferous/palm trees) is being asked of all lifeform types eg lichens
- [ ] When I go backwards it doesn't 'forget' my answer, I think it should as it's quite confusing otherwise
- [ ] I wonder if we should have a 'can't be bothered to answer any more questions' button?! (Would need to rethink the button name!)
- [ ] The what is approx field size question doesn't indicate for example xm by ym dimension to help people or maybe use hectares?
- [ ] In water regime rather than questions make these statements e.g. it is waterlogged and tell them at the top 'tick most appropriate'
- [ ] Same with wetness as above and whether or not it's 'waterbody' 'water source' 'estuary' etc ie don't make them questions.
- [ ] Stuck on wetness page i.e. 'next' isn't working
- [ ] Shouldn't be allowed to leave & cover, (ha) field size and height (m) as 'zeros' ie. can leave these and not change from the default and still click next, should HAVE to fill something in here
cultivated>graminoids takes me to the question is it broadleaved/confierous/palm trees which, in a grassy field I don't think is right…should maybe jump straight to the & cover question
- [ ] Instead of 'it is' at the top of the questions maybe more appropriate would be 'select the most appropriate'
- [ ] I used the 'back' button at the end of one of my sessions and then it froze again on the first page like it did in number 1 above
- [ ] Would it be possible/useful to make it automatically go to the next page after and answer is put in rather than have to select 'Next'
- [ ] Change crown cover % (as this is used for trees) to just 'vegetation % cover'
re the option to add info on an extra layer of vegetation, allow for max a second layer (for now!)

**Comment by rgamez** [comment]
2, 3, 6, 10, 14 Already fixed in the eo.json that I used as starting point
4. discussed this and decided it is useful to retain old answers.
5. Discussed this and think there is merit in an 'exit' button

**Comment by rgamez** [comment]
13. Added side buttons to move easier to the prev/next question

**Comment by panterz** [comment]
Transfer it outside of milestone 2 since it's no  necessary for the time being.

**Comment by panterz** [comment]
Implementation has been frozen by COBWEB.
