### ISSUE TITLE
HTML form to json or survey.json

### ISSUE THREAD

**Issue by panterz** [edina/fieldtrip-cobweb-project#54]
COBWEB has given some few extra requirements. Some extra elements should be predefined inside the form in order the user to download them when he/she downloads the form.
- decision tree (json file) that is attached to the form:
```
<input type="hidden" data-dtree="editors/111-222-333-444.json"></div>
```
- layer (kml,mbtiles) that is related to the form and is being downloaded to the device when the form is downloaded
```
<input type="hidden" data-layers="dyfi.mbtiles">
```
- bbox that should be predefined by the AT and should be the default location for when the GPS is timed out
```
<input type="hidden" data-bbox="22.311806872606873,40.02559816362384,22.496514514208435,40.15009980462884">
```
- I introduced new types of geometries for capturing records such as record.
```
<input type="hidden" data-record-geometry="point,polygon">
```

So the big question is if we should go for a json file that will include all these elements and the html form will be rendered with fields that are coming from this json file or we can just create a survey.json that will have the path of the html form.

**Comment by benismobile** [comment]
seems to me some of these (e.g. GPS timeout fallback location) relate more to application level configuration.

**Comment by xmichael** [comment]
> So the big question is if we should go for a json file that will include all these elements and the html 
> form will be rendered with fields that are coming from this json file or we can just create a survey.json > that will have the path of the html form.

It seems that the less files we have the better in order to avoid any synchronization and parsing problems. As far as cobweb is concerned, the move from html to json will enable us to:

 - separate content from presentation. 
 - parse json instead of html for survey options
 - embed decision tree configuration inside the survey.json instead of having sparse files

In any case the html5 should be fairly easy to generate from json using a template (or even string substitution).

**Comment by panterz** [comment]
We have done this. There's a survey.json. I need to add it on the wiki.
